# Generated by Django 5.0.3 on 2024-03-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
