# Generated by Django 5.0.3 on 2024-03-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
